In [ ]:
import mysql.connector
import pandas as pd

#DB 접속 정보
'''db_config = {
    'host': "54.66.228.99",
    'user': "root",
    'password': "ai-challenge-1234",
    'database': "ai_challenge",
    'port': 3306 # 받으신 포트 번호가 다르다면 수정해주세요.
}
'''
# ----------------------------------------------------------------

#DB에서 가져올 데이터에 대한 SQL 쿼리 정의

# 스케쥴 테이블
query_schedule = "SELECT * FROM schedule;"

# 카드 + 혜택 테이블
query_card_benefits = """SELECT * FROM card c JOIN benefit b ON c.card_id=b.card_id """


df_schedule = pd.DataFrame()
df_card_benefits = pd.DataFrame()
connection = None
try:
    connection = mysql.connector.connect(**db_config)
    print("✅ DB 연결 성공!")
    
    df_schedule = pd.read_sql(query_schedule, connection)
    print(f"✅ 스케쥴 데이터 {len(df_schedule)}건 로딩 완료!")
    
    df_card_benefits = pd.read_sql(query_card_benefits, connection)
    print(f"✅ 카드+혜택 데이터 {len(df_card_benefits)}건 로딩 완료!")

except Exception as e:
    print(f"❌ 데이터 로딩 중 에러 발생: {e}")
    print("-> DB 접속 정보나 SQL 쿼리의 테이블/컬럼 이름이 정확한지 확인해주세요.")
finally:
    if connection and connection.is_connected():
        connection.close()
        print("✅ DB 연결이 안전하게 종료되었습니다.")

print("\n--- [확인] 스케쥴 데이터 (상위 3개) ---")
display(df_schedule.head(3))

print("\n--- [확인] 카드+혜택 데이터 (상위 3개) ---")
display(df_card_benefits.head(3))

✅ DB 연결 성공!

C:\Users\i0215531\AppData\Local\Temp\ipykernel_10592\1617058760.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_schedule = pd.read_sql(query_schedule, connection)

✅ 스케쥴 데이터 3건 로딩 완료!

C:\Users\i0215531\AppData\Local\Temp\ipykernel_10592\1617058760.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_card_benefits = pd.read_sql(query_card_benefits, connection)

✅ 카드+혜택 데이터 77건 로딩 완료!
✅ DB 연결이 안전하게 종료되었습니다.

--- [확인] 스케쥴 데이터 (상위 3개) ---

,schedule_id,created_at,is_deleted,modified_at,schedule_color,schedule_end_date,schedule_frequency,schedule_is_checklist,schedule_name,schedule_repeat_end_date,schedule_repeat_start_date,schedule_start_date,user_id
0,1,2025-08-31 00:23:05.766721,0,2025-08-31 00:23:05.766721,#FF5733,2025-08-31 23:00:00,NONE,0,개발 공부,NaT,NaT,2025-08-31 22:00:00,b'\x89\xdb\xf5>\xc7EE\xe0\x88\x07;\x11#-\xbb\xb9'
1,2,2025-08-31 00:23:14.303708,0,2025-08-31 00:23:14.303708,#FF5733,2025-07-25 11:00:00,MONTHLY,0,월급날,2026-08-21 12:00:00,2025-07-25 11:00:00,2025-07-25 11:00:00,b'\x89\xdb\xf5>\xc7EE\xe0\x88\x07;\x11#-\xbb\xb9'
2,3,2025-08-30 15:26:35.704191,0,2025-08-30 15:26:35.704191,#FF5733,2025-08-01 05:00:00,WEEKLY,0,점심 회의,2025-11-30 15:00:00,2025-08-01 04:00:00,2025-08-01 04:00:00,b'\x89\xdb\xf5>\xc7EE\xe0\x88\x07;\x11#-\xbb\xb9'

--- [확인] 카드+혜택 데이터 (상위 3개) ---

,card_id,created_at,is_deleted,modified_at,card_annual_fee_domestic,card_annual_fee_international,card_benefit_limit,card_category,card_name,benefit_id,...,benefit_amount_limit,benefit_category,benefit_content,benefit_frequency_type,benefit_max_amount,benefit_min_amount,benefit_percent,benefit_times,benefit_type,card_id
0,1,2025-09-05 05:12:37,0,2025-09-05 05:12:37,15000,18000,None,CREDIT,신한카드 Mr.Life,1,...,3000.0,UTILITY_BILLS_RENTAL,"전기요금 /도시가스요금/ SKT, LG U+, KT 통신요금 할인",MONTHLY,500000.0,300000.0,10.0,NaN,BILLING_DISCOUNT,1
1,1,2025-09-05 05:12:37,0,2025-09-05 05:12:37,15000,18000,None,CREDIT,신한카드 Mr.Life,2,...,7000.0,UTILITY_BILLS_RENTAL,"전기요금 /도시가스요금/ SKT, LG U+, KT 통신요금 할인",MONTHLY,1000000.0,500000.0,10.0,NaN,BILLING_DISCOUNT,1
2,1,2025-09-05 05:12:37,0,2025-09-05 05:12:37,15000,18000,None,CREDIT,신한카드 Mr.Life,3,...,10000.0,UTILITY_BILLS_RENTAL,"전기요금 /도시가스요금/ SKT, LG U+, KT 통신요금 할인",MONTHLY,NaN,1000000.0,10.0,NaN,BILLING_DISCOUNT,1

In [ ]:
# 이 셀은 LLM API를 호출하여 스케쥴의 핵심 카테고리를 분석하는 함수를 정의합니다.
from openai import OpenAI

# --- LLM API Key 설정 ---
# 발급받은 OpenAI API Key를 여기에 붙여넣으세요.
# (실제 서비스에서는 이 키를 코드에 직접 노출하면 안 되지만, 지금은 테스트 목적입니다.)
#client = OpenAI(api_key = "ㅌ")

# -----------------------------------------------------------

# --- AI의 핵심 두뇌 함수 (최종 표준 버전) ---
def get_recommendation_final(schedule_name, knowledge_df):
    
    # --- 백엔드와 약속된 '정답지' (카드 혜택 카테고리 목록) ---
    BENEFIT_CATEGORIES = [
        "ALL_MERCHANTS", "TRANSPORTATION", "FUEL", "TELEPHONE_CHARGE", "MART_CONVENIENCE_STORE", 
        "ONLINE_SHOPPING", "SHOPPING", "FOOD", "CAFE_DESSERT", "BEAUTY_FITNESS", 
        "NO_SPENDING_REQUIREMENT", "UTILITY_BILLS_RENTAL", "HOSPITAL_PHARMACY", "PETS", 
        "EDUCATION_CHILDCARE", "AUTOMOBILE_HI_PASS", "LEISURE_SPORTS", "DIGITAL_SUBSCRIPTION", 
        "MOVIES_CULTURE", "EASY_PAYMENT", "AIRLINE_MILEAGE", "AIRPORT_LOUNGE_PRIORITY_PASS", 
        "PREMIUM", "TRAVEL_ACCOMMODATION", "OVERSEAS", "BUSINESS", "ETC"
    ]
    
    prompt = f"""
        당신은 사용자의 캘린더 일정을 분석하여 가장 관련 있는 소비 카테고리를 찾아주는 AI입니다.
        아래 "카테고리 목록" 중에서 "{schedule_name}"라는 일정 내용과 가장 관련 깊은 것 단 하나만 골라, 
        다른 설명은 일절 없이, 반드시 영어 카테고리 이름으로만 대답해주세요.
        만약 관련 있는 카테고리가 없다면 'ETC'라고 대답하세요.

        --- 카테고리 목록 ---
        {', '.join(BENEFIT_CATEGORIES)}
    """
    try:
        # 표준 v1.0.0 방식의 API 호출
        response = client.chat.completions.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0
        )
        llm_category = response.choices[0].message.content.strip()
        if llm_category not in BENEFIT_CATEGORIES: llm_category = "ETC"
    except Exception as e:
        print(f"LLM 분석 실패: {e}")
        llm_category = "ETC"

    if llm_category != "ETC":
        result_df = knowledge_df[knowledge_df['benefit_category'] == llm_category]
        if not result_df.empty:
            top_card = result_df.iloc[0]
            return f"▶ '{llm_category}' 혜택! [{top_card['card_name']}] 카드의 '{top_card['benefit_info']}' 혜택을 추천합니다!"
        else:
            return f"'{llm_category}' 카테고리의 혜택은 있으나, 현재 보유한 지식 내에 적합한 카드가 없습니다."
    return "연관된 카드 혜택을 찾지 못했습니다."

===== 🤖 [최종 버전] AI 캘린더 에이전트 추천 시뮬레이션 시작 🤖 =====
LLM 분석 실패: Connection error.

🗓️ 입력된 일정: 개발 공부
💬 AI의 추천: 연관된 카드 혜택을 찾지 못했습니다.
------------------------------------------------------------
LLM 분석 실패: Connection error.

🗓️ 입력된 일정: 월급날
💬 AI의 추천: 연관된 카드 혜택을 찾지 못했습니다.
------------------------------------------------------------
LLM 분석 실패: Connection error.

🗓️ 입력된 일정: 점심 회의
💬 AI의 추천: 연관된 카드 혜택을 찾지 못했습니다.
------------------------------------------------------------

In [ ]:
print("===== 🤖 [최종 버전] AI 캘린더 에이전트 추천 시뮬레이션 시작 🤖 =====")

# 1단계에서 로드한 모든 스케쥴을 하나씩 AI에게 물어봅니다.
for index, schedule in df_schedule.iterrows():
    schedule_name = schedule['schedule_name']
    
    # 2단계에서 만든 AI 두뇌 함수를 호출하여 추천 결과를 받습니다.
    recommendation = get_recommendation_final(schedule_name, df_card_benefits)
    
    # 결과를 출력합니다.
    print(f"\n🗓️ 입력된 일정: {schedule_name}")
    print(f"💬 AI의 추천: {recommendation}")
    print("-" * 60)

print("\n===== ✅ 시뮬레이션이 성공적으로 완료되었습니다. =====")

===== 🤖 [최종 버전] AI 캘린더 에이전트 추천 시뮬레이션 시작 🤖 =====
LLM 분석 실패: Missing required arguments; Expected either ('input' and 'model') or ('input', 'model' and 'stream') arguments to be given

🗓️ 입력된 일정: 개발 공부
💬 AI의 추천: 연관된 카드 혜택을 찾지 못했습니다.
------------------------------------------------------------
LLM 분석 실패: Missing required arguments; Expected either ('input' and 'model') or ('input', 'model' and 'stream') arguments to be given

🗓️ 입력된 일정: 월급날
💬 AI의 추천: 연관된 카드 혜택을 찾지 못했습니다.
------------------------------------------------------------
LLM 분석 실패: Missing required arguments; Expected either ('input' and 'model') or ('input', 'model' and 'stream') arguments to be given

🗓️ 입력된 일정: 점심 회의
💬 AI의 추천: 연관된 카드 혜택을 찾지 못했습니다.
------------------------------------------------------------

===== ✅ 시뮬레이션이 성공적으로 완료되었습니다. =====

In [9]:
!curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - �ش� �Լ����� �������� ���� �ı� ���θ� �˻����� ���߽��ϴ�.